language: r
cache: packages
dist: trusty
sudo: false
warnings_are_errors: true
bioc_required: true
before_install:
- Rscript -e 'update.packages(ask = FALSE)'
r_github_packages:
- jimhester/lintr
notifications:
  slack:
    secure: sw/He3WX7Fs61DTufgG9hx7fWDhwx57zv+dYB4sr30LgKyIJNbZYSU76ZN4oPwHFGAJ0eyk/22XCuKF8/seSB2ArQuc4kFlsaeWWg1CxDqW9iR0zs91MJL3lJoUOSayy5WcWbsUxD+x8GcB37FCgoTXcveN956bfgrDb2nGrFY6QMSVsnkWi/kiMdzhR4VPzOfmAUZUcr1aDU3WN4ROwbDg89zCfu9HbVKZwyQdYZk7L2Pgg8xGIcGZkaMN1MMD/r0Wc2aVYqCOcn5qO/9CaspEBf7cd6ejVzgAl/LM4dTIPlx9E6ekQGwJXpt1Qxyc0sqVSQWFZvFkWyV3wkqX8pfSXV6ojlP2cGJt+PSQXwLHj0TKWYx7yHbw+55da/b//SVLZVHl+P6VXxQBe2hmFD6sCk3V3uq2CkxzI52bK4Wv4RRncVKIZEpFZOc9P2ik5mf6pICmLHwttlbHeDjJbQ+raYftF704xb1sOxapLwuy+c2SWKPeqOiimfZNgOK+J7JbvQvpnaiHN+3CA3wQXs1auKBwI+swvsZPAzeKssnLv/0AQmX8ckVzvXJzUvl1J73c9V2zG2F44xmIsXwzruEp6leSbeXcLifrfbfQdmaHzq4M/Z83o/fwGRzdWfG7YXDyPIabik7DOMrSUvF+wLGVTjOart8HrA4eVEkKFnRE=
r_packages:
- covr
after_success:
- Rscript -e 'library(covr); codecov()'
env:
  global:
  - secure: uKZUbfGfk7wBdinNFDyivyUgDt6NS0BMQhBNkBWnEWI65NH88qC6ekHmbhdtJUa7DnuOS7S97uN4fuBTNtLbOymffMIWKmA8FbmrLgt1xgGuE01EcgZscXqfkGGyeQdC3Jiz768ya7mKLM4K4Oql8ITnugWMdZYxQuA4iLEzsnVXMrNyEwZYUk5tFHKsAhL8U7TRgxcvjePP8LBRKuJT1ac6oyi7KTbz8R88LOzJX4mGra9DTXx2CUDdYEresDxF7iU/ooWMQfy6hV97PS45Kltj1Enf6XAjkd2FqbpFXLxvCO80JwhFsqID0Y5lYiITv52wCi5ehTiWh8kVGGeYbh99J9ITAO5c9yYP/2B0p9HsCdOYeek9ci4e4Si9V5wf2yDIs7UpFpwOu6gkpUwWux1tc16DS+TBKLnMNVfNQepa5OkncnONkiiXVuqN0JmvVw3ZYZZklpfdBqSG8neMTosUa8TXynHzvFgTtS8UCnVQIbH1VxjNBLJCAOnrx+HF2th6CG1A916PP3vGo+Jc0KhpE1gsKPJ/k+rrXrfsl8Tifmkm3JNWlLL2k8CO1EvkV+MmGZ0kUin1sobwmsBMG023G9BlBA+rwTZ/g4FANyzDdB9O1jMEWjUkEpgentU+C4DIA4SF+nGggVVlOz4zXKierrZnVzQi+kKDu8sCFWI=
